export const UPDATE_USER = 'UPDATE_USER';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const UPDATE_MENU_ITEMS = 'UPDATE_MENU_ITEMS';
export default {
  UPDATE_USER,
  TOGGLE_DRAWER,
  UPDATE_MENU_ITEMS
}