export const TOGGLE_RIGHT_DRAWER = 'TOGGLE_RIGHT_DRAWER';
export const SET_DRAWER_MODEL="SET_DRAWER_MODEL";
export const SET_DRAWER_MODEL_COLUMNS = 'SET_DRAWER_MODEL_COLUMNS';
export default {
  TOGGLE_RIGHT_DRAWER,
  SET_DRAWER_MODEL,
  SET_DRAWER_MODEL_COLUMNS
}